FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libreoffice \
    fonts-nanum \
    fonts-noto-cjk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && fc-cache -fv

WORKDIR /python

COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./python /python

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
