FROM python:3.10-slim

WORKDIR /python-stt

COPY python-stt/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./python-stt /python-stt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
